# -*- coding: utf-8 -*-
"""parkinson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhmO5hBpnV5KtloMLF5Mz5snspLt7cEY
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv("/parkinsons.data")

print("\n=== DATASET OVERVIEW ==\n")
print("Dataset Shape (Rows, Columns):", data.shape)

print("\nFirst 5 Rows of Dataset:\n")
print(data.head())

print("\nDataset Information:\n")
print(data.info())

print("\nTarget Class Distribution (status):")
print("1 → Parkinson’s Disease")
print("0 → Healthy\n")
print(data["status"].value_counts())

# 2. Select Important Features (ONLY 5)
selected_features = [
    "MDVP:Fo(Hz)",
    "MDVP:Fhi(Hz)",
    "MDVP:Flo(Hz)",
    "HNR",
    "PPE"
]

X = data[selected_features]
y = data["status"]

print("\nSelected Features:\n", selected_features)

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 5. Model Training (SVM)
model = SVC(kernel="rbf", C=1.0, gamma="scale")
model.fit(X_train, y_train)

# 6. Model Evaluation
y_pred = model.predict(X_test)

print("\n MODEL PERFORMANCE\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}\n")

print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# 7. User Input Prediction (ONLY 5 VALUES)
print("\nUSER PREDICTION \n")
print("Enter the following voice feature values:\n")

user_values = []
for feature in selected_features:
    value = float(input(f"{feature}: "))
    user_values.append(value)

user_data = np.array(user_values).reshape(1, -1)
user_data_scaled = scaler.transform(user_data)

prediction = model.predict(user_data_scaled)

print("\nPREDICTION RESULT\n")
if prediction[0] == 1:
    print(" Result: Parkinson’s Disease Detected")
else:
    print("Result: No Parkinson’s Disease Detected")

print("\nDisclaimer: For educational use only.")